server:
  port: 18080

mybatis.config-locations:classpath: mybatis/mybatis-config.xml
mybatis.mapper-locations:classpath: mybatis/mapper/*.xml
mybatis.type-aliases-package: com.neo.entity

spring.datasource.driverClassName : com.mysql.jdbc.Driver
spring.datasource.url : jdbc:mysql://127.0.0.1:3306/flyway?useLegacyDatetimeCode=false&serverTimezone=Asia/Hong_Kong&useSSL=false
spring.datasource.username : root
spring.datasource.password : 123456

# 数据库版本控制
flyway:
  enabled: true
  # 若连接的数据库非空库，是否初始化
  baseline-on-migrate: true
   # 是否开启校验
  validate-on-migrate: false
  # 默认脚本加载路径：/db/migration
  # locations=classpath:/db/migration

