
package com.webclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SayWeb", targetNamespace = "http://webserver.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SayWeb {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://webserver.com/", className = "com.webclient.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://webserver.com/", className = "com.webclient.SayHelloResponse")
    @Action(input = "http://webserver.com/SayWeb/sayHelloRequest", output = "http://webserver.com/SayWeb/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "sayBye", targetNamespace = "http://webserver.com/", className = "com.webclient.SayBye")
    @ResponseWrapper(localName = "sayByeResponse", targetNamespace = "http://webserver.com/", className = "com.webclient.SayByeResponse")
    @Action(input = "http://webserver.com/SayWeb/sayByeRequest", output = "http://webserver.com/SayWeb/sayByeResponse")
    public void sayBye();

}
