
package com.webclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SayWebService", targetNamespace = "http://webserver.com/", wsdlLocation = "http://localhost:8080/MyService/ServiceTest?wsdl")
public class SayWebService
    extends Service
{

    private final static URL SAYWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException SAYWEBSERVICE_EXCEPTION;
    private final static QName SAYWEBSERVICE_QNAME = new QName("http://webserver.com/", "SayWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/MyService/ServiceTest?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAYWEBSERVICE_WSDL_LOCATION = url;
        SAYWEBSERVICE_EXCEPTION = e;
    }

    public SayWebService() {
        super(__getWsdlLocation(), SAYWEBSERVICE_QNAME);
    }

    public SayWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SAYWEBSERVICE_QNAME, features);
    }

    public SayWebService(URL wsdlLocation) {
        super(wsdlLocation, SAYWEBSERVICE_QNAME);
    }

    public SayWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SAYWEBSERVICE_QNAME, features);
    }

    public SayWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SayWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SayWeb
     */
    @WebEndpoint(name = "SayWebPort")
    public SayWeb getSayWebPort() {
        return super.getPort(new QName("http://webserver.com/", "SayWebPort"), SayWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SayWeb
     */
    @WebEndpoint(name = "SayWebPort")
    public SayWeb getSayWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webserver.com/", "SayWebPort"), SayWeb.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAYWEBSERVICE_EXCEPTION!= null) {
            throw SAYWEBSERVICE_EXCEPTION;
        }
        return SAYWEBSERVICE_WSDL_LOCATION;
    }

}
